# Generated by Django 6.0.5 on 2026-05-31 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('email_fornecedor', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_fornecedor', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inativacao', models.DateField(blank=True, null=True)),
                ('data_registo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=255)),
                ('email_funcionario', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo_funcionario', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inativacao', models.DateField(blank=True, null=True)),
                ('data_registo', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id_peca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_peca', models.CharField(max_length=255)),
                ('descricao_peca', models.TextField(blank=True, null=True)),
                ('custo_peca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quant_peca', models.IntegerField(default=0)),
                ('alerta_quant', models.IntegerField(default=5)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inativacao', models.DateField(blank=True, null=True)),
                ('data_registo', models.DateField(auto_now_add=True)),
                ('fornecedores', models.ManyToManyField(blank=True, related_name='pecas', to='oficinatech01.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('quant_entrada', models.IntegerField()),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='oficinatech01.fornecedor')),
                ('id_peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='oficinatech01.peca')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('quant_venda', models.IntegerField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='oficinatech01.funcionario')),
                ('id_peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='oficinatech01.peca')),
            ],
        ),
    ]
